# Generated by Django 4.0 on 2022-11-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_EN', models.CharField(blank=True, max_length=50, null=True)),
                ('name_CN', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_EN', models.CharField(blank=True, max_length=50, null=True)),
                ('name_CN', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_EN', models.CharField(blank=True, max_length=50, null=True)),
                ('name_CN', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_EN', models.CharField(blank=True, max_length=50, null=True)),
                ('name_CN', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_EN', models.CharField(blank=True, max_length=50, null=True)),
                ('name_CN', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('dspace_uri', models.URLField(max_length=250)),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
                ('pub_year', models.IntegerField(blank=True, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('genre', models.ManyToManyField(to='ads.MediaType')),
                ('prod_cat', models.ManyToManyField(to='ads.ProductCategory')),
                ('prod_type', models.ManyToManyField(to='ads.ProductType')),
                ('spatial_coverage', models.ManyToManyField(to='ads.Place')),
                ('subject', models.ManyToManyField(to='ads.Subject')),
            ],
        ),
    ]
