# Generated by Django 4.0 on 2022-11-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_collection_advertisement_owning_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='uid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
