# Generated by Django 4.0 on 2022-11-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_rename_subtitle_advertisement_subtitle_cn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='space_iiif_id',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='dspace_uri',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
