# Generated by Django 4.0 on 2022-11-02 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_advertisement_space_iiif_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='space_iiif_id',
            new_name='dspace_iiif_uri',
        ),
    ]
