user="..."
password="..."
base_dspace_items_url="https://.../items/"
base_dspace_iiif_url="https://.../server/iiif/"
base_dspace_api_url="https://.../server/api/"
targeted_collections_uuids=[
	'123-456-789-012-345',
	...
]
cert="...-chain.pem"
AWS_S3_ACCESS_KEY_ID='...'
AWS_S3_SECRET_ACCESS_KEY='...'
AWS_STORAGE_BUCKET_NAME='...'