from django.contrib import admin
from metadata.models import *

admin.site.register(DcTitleSubtitle)
admin.site.register(DspaceIiifEnabled)
admin.site.register(DcIdentifierDigital)
admin.site.register(DcDescriptionFulltext)
admin.site.register(DcLanguageIso)
admin.site.register(DcCoverageSpatial)
admin.site.register(DcFormatMedium)
admin.site.register(DcTypeDcmi)
admin.site.register(DcSubjectBrand)
admin.site.register(DcTypeGenre)
admin.site.register(DcTitle)
admin.site.register(DcSubjectProdcat)
admin.site.register(DcDateAccessioned)
admin.site.register(DcDateIssued)
admin.site.register(DcSubject)
admin.site.register(DcDateCreated)
admin.site.register(DcDescriptionProvenance)
admin.site.register(DcIdentifierUri)
admin.site.register(DcDescription)
admin.site.register(DcPublisher)
admin.site.register(DcDigitizationSpecifications)
admin.site.register(DcDateAvailable)
admin.site.register(DcSourceCollection)
admin.site.register(DcSubjectProdtype)
