# Generated by Django 4.2 on 2023-04-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcdescriptionfulltext',
            name='text_CN',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcdescriptionfulltext',
            name='text_EN',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcdescriptionfulltext',
            name='text_original',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcdescriptionprovenance',
            name='text_CN',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcdescriptionprovenance',
            name='text_EN',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcdescriptionprovenance',
            name='text_original',
            field=models.TextField(blank=True, null=True),
        ),
    ]
