# Generated by Django 4.2 on 2023-04-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_remove_publishedadvertisement_dc_citation_issuenumbers_and_more'),
        ('metadata', '0002_alter_dcdescriptionfulltext_text_cn_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DcCitationIssuenumber',
        ),
        migrations.DeleteModel(
            name='DcCitationPagenumber',
        ),
        migrations.DeleteModel(
            name='DcCitationVolumenumber',
        ),
        migrations.DeleteModel(
            name='DcContributorFunder',
        ),
        migrations.DeleteModel(
            name='DcContributorPublisher',
        ),
        migrations.DeleteModel(
            name='DcDateDigital',
        ),
        migrations.DeleteModel(
            name='DcDescriptionPosition',
        ),
        migrations.DeleteModel(
            name='DcRelationIspartofseries',
        ),
        migrations.DeleteModel(
            name='DcRights',
        ),
        migrations.DeleteModel(
            name='DcRightsUri',
        ),
        migrations.DeleteModel(
            name='DcSource',
        ),
        migrations.DeleteModel(
            name='DcSubjectAdcat',
        ),
    ]
