# Generated by Django 4.0 on 2022-11-02 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='owning_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.collection'),
        ),
    ]
