# Generated by Django 4.2 on 2023-04-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_stagedphoto_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedadvertisement',
            name='review_begun',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stagedadvertisement',
            name='review_finished',
            field=models.BooleanField(default=False),
        ),
    ]
