# Generated by Django 4.2 on 2023-04-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_remove_publishedadvertisement_chao_company_addresss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedadvertisement',
            name='dc_citation_issueNumbers',
        ),
        migrations.RemoveField(
            model_name='publishedadvertisement',
            name='dc_citation_pageNumbers',
        ),
        migrations.RemoveField(
            model_name='publishedadvertisement',
            name='dc_citation_volumeNumbers',
        ),
        migrations.RemoveField(
            model_name='publishedadvertisement',
            name='dc_contributor_funders',
        ),
        migrations.RemoveField(
            model_name='publishedadvertisement',
            name='dc_contributor_publishers',
        ),
        migrations.RemoveField(
            model_name='publishedadvertisement',
            name='dc_date_digitals',
        ),
        migrations.RemoveField(
            model_name='publishedadvertisement',
            name='dc_description_positions',
        ),
        migrations.RemoveField(
            model_name='publishedadvertisement',
            name='dc_relation_IsPartOfSeriess',
        ),
        migrations.RemoveField(
            model_name='publishedadvertisement',
            name='dc_rights_uris',
        ),
        migrations.RemoveField(
            model_name='publishedadvertisement',
            name='dc_rightss',
        ),
        migrations.RemoveField(
            model_name='publishedadvertisement',
            name='dc_sources',
        ),
        migrations.RemoveField(
            model_name='publishedadvertisement',
            name='dc_subject_adcats',
        ),
        migrations.RemoveField(
            model_name='stagedadvertisement',
            name='dc_citation_issueNumbers',
        ),
        migrations.RemoveField(
            model_name='stagedadvertisement',
            name='dc_citation_pageNumbers',
        ),
        migrations.RemoveField(
            model_name='stagedadvertisement',
            name='dc_citation_volumeNumbers',
        ),
        migrations.RemoveField(
            model_name='stagedadvertisement',
            name='dc_contributor_funders',
        ),
        migrations.RemoveField(
            model_name='stagedadvertisement',
            name='dc_contributor_publishers',
        ),
        migrations.RemoveField(
            model_name='stagedadvertisement',
            name='dc_date_digitals',
        ),
        migrations.RemoveField(
            model_name='stagedadvertisement',
            name='dc_description_positions',
        ),
        migrations.RemoveField(
            model_name='stagedadvertisement',
            name='dc_relation_IsPartOfSeriess',
        ),
        migrations.RemoveField(
            model_name='stagedadvertisement',
            name='dc_rights_uris',
        ),
        migrations.RemoveField(
            model_name='stagedadvertisement',
            name='dc_rightss',
        ),
        migrations.RemoveField(
            model_name='stagedadvertisement',
            name='dc_sources',
        ),
        migrations.RemoveField(
            model_name='stagedadvertisement',
            name='dc_subject_adcats',
        ),
    ]
