# Generated by Django 4.2 on 2023-04-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_rename_space_iiif_id_advertisement_dspace_iiif_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='iiif_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
