# Generated by Django 4.2 on 2023-04-11 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_advertisement_iiif_enabled_advertisement_is_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StagedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=50, null=True)),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='prod_cat',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='prod_type',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='subject',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='ads.mediatype'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='prod_cats',
            field=models.ManyToManyField(blank=True, null=True, to='ads.productcategory'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='prod_types',
            field=models.ManyToManyField(blank=True, null=True, to='ads.producttype'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='ads.subject'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='spatial_coverage',
            field=models.ManyToManyField(blank=True, null=True, to='ads.place'),
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('languages', models.ManyToManyField(to='ads.language')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.stagedmedia'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='transcriptions',
            field=models.ManyToManyField(blank=True, null=True, to='ads.transcription'),
        ),
    ]
