# Generated by Django 4.2 on 2023-04-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_alter_advertisement_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='photo',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='staged_photo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='StagedMedia',
        ),
    ]
