# Generated by Django 4.2 on 2023-04-11 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_remove_advertisement_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='parent_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.collection'),
        ),
    ]
