# Generated by Django 4.2 on 2023-04-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_collection_name_collection_parent_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='dspace_uri',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
