# Generated by Django 4.2 on 2023-04-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_collection_dspace_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='staged_photo',
            field=models.FileField(blank=True, null=True, upload_to='staged_photos/'),
        ),
    ]
