# Generated by Django 4.2 on 2023-04-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_alter_advertisement_staged_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='human_reviewd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transcription',
            name='machine_generated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, to='ads.language'),
        ),
    ]
