# Generated by Django 4.2 on 2023-04-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_transcription_human_reviewd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='genres',
            field=models.ManyToManyField(blank=True, to='ads.mediatype'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='prod_cats',
            field=models.ManyToManyField(blank=True, to='ads.productcategory'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='prod_types',
            field=models.ManyToManyField(blank=True, to='ads.producttype'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='spatial_coverage',
            field=models.ManyToManyField(blank=True, to='ads.place'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='ads.subject'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='transcriptions',
            field=models.ManyToManyField(blank=True, to='ads.transcription'),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='languages',
            field=models.ManyToManyField(blank=True, to='ads.language'),
        ),
    ]
