# Generated by Django 4.2 on 2023-04-11 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_alter_advertisement_genres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='transcriptions',
        ),
        migrations.AddField(
            model_name='transcription',
            name='advertisement',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='ads.advertisement'),
            preserve_default=False,
        ),
    ]
