# Generated by Django 4.2 on 2023-04-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_advertisement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='description_fulltext',
            field=models.TextField(blank=True, null=True),
        ),
    ]
